/**
 * Generates public/vine.svg.
 *
 * Leaf and petiole placement is computed against the stem curve rather than
 * eyeballed: each leaf is hung off the point on the stem at a target y, so a
 * petiole can never float free of the stem the way hand-placed ones drift when
 * the curve is edited.
 */
import { writeFileSync } from "node:fs";

// Stem as a chain of cubics. Each entry is [c1, c2, end]; the run starts at P0.
const P0 = [100, 0];
const SEGMENTS = [
  [[130, 60], [70, 110], [96, 170]],
  [[122, 230], [62, 280], [88, 340]],
  [[114, 400], [66, 450], [92, 510]],
  [[118, 570], [64, 620], [90, 680]],
  [[110, 730], [76, 772], [90, 800]],
];

const cubic = (p0, c1, c2, p3, t) => {
  const u = 1 - t;
  const a = u * u * u, b = 3 * u * u * t, c = 3 * u * t * t, d = t * t * t;
  return [
    a * p0[0] + b * c1[0] + c * c2[0] + d * p3[0],
    a * p0[1] + b * c1[1] + c * c2[1] + d * p3[1],
  ];
};

// Dense polyline of the whole stem, used to look up x at a given y.
const samples = [];
let start = P0;
for (const [c1, c2, end] of SEGMENTS) {
  for (let i = 0; i <= 100; i++) samples.push(cubic(start, c1, c2, end, i / 100));
  start = end;
}
const stemXAt = (y) => {
  let best = samples[0];
  for (const p of samples) {
    if (Math.abs(p[1] - y) < Math.abs(best[1] - y)) best = p;
  }
  return best[0];
};

// side: 1 hangs the leaf to the right of the stem, -1 to the left.
const LEAVES = [
  { y: 45, side: 1, scale: 1.0 },
  { y: 105, side: -1, scale: 0.95 },
  { y: 180, side: 1, scale: 0.92 },
  { y: 250, side: -1, scale: 0.9 },
  { y: 325, side: 1, scale: 0.88 },
  { y: 395, side: -1, scale: 0.85 },
  { y: 462, side: 1, scale: 0.82 },
  { y: 530, side: -1, scale: 0.8 },
  { y: 600, side: 1, scale: 0.78 },
  { y: 668, side: -1, scale: 0.75 },
  { y: 735, side: 1, scale: 0.72 },
];

const r2 = (n) => Math.round(n * 10) / 10;
const petioles = [];
const uses = [];

for (const { y, side, scale } of LEAVES) {
  const sx = stemXAt(y);
  const lx = sx + side * 44 * scale;
  const ly = y + 8 * scale;
  const rot = side === 1 ? 37 : -42;
  petioles.push(`      <path d="M${r2(sx)} ${r2(y)} L${r2(lx)} ${r2(ly)}"/>`);
  uses.push(
    `    <use href="#leaf" transform="translate(${r2(lx)} ${r2(ly)}) rotate(${rot}) scale(${scale})"/>`,
  );
}

// The leaf at the bottom edge. Centred on the stem rather than hung to one
// side, and low enough that the viewport crops it — a leaf running off the
// edge reads as a vine that carries on past the page, where a stem running off
// the edge just reads as a cut wire.
const tipX = stemXAt(788);
uses.push(
  `    <use href="#leaf" transform="translate(${r2(tipX)} 788) rotate(9) scale(0.7)"/>`,
);

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 800" width="200" height="800">
  <!--
    Trailing pothos / heartleaf philodendron, used as a CSS mask, so only the
    alpha channel matters.

    A vine suits a backdrop better than a single blade: it is a line rather
    than a mass, so it traces the edge of the page instead of sitting as a
    pale field behind the cards.

    It runs the FULL height of the viewport and its last leaf straddles the
    bottom edge. An earlier version was 500 units tall and stopped around
    halfway down the screen, which read as cut off however the end was
    finished — the problem was never the tip, it was a vine hanging in empty
    space with nothing below it. A plant leaving the frame needs to leave it at
    an edge.

    The top is left open on purpose: that end sits above the viewport, behind
    the nav band, so it is never seen.

    Generated by scripts/gen-vine.mjs — leaves are hung off computed points on
    the stem, so editing the curve cannot leave a petiole floating. Stems are
    stroked rather than outlined; a mask samples rendered alpha, so a stroke is
    as good as a fill and keeps the file small.
  -->
  <defs>
    <!-- Cordate leaf: apex at the bottom, notch at the top where it meets the
         petiole. Two lobes curving into the notch, no straight segments. -->
    <path id="leaf" d="M0 40
                       C-20 24 -34 8 -34 -8
                       C-34 -24 -18 -32 -6 -22
                       C-3 -19 -1 -16 0 -12
                       C1 -16 3 -19 6 -22
                       C18 -32 34 -24 34 -8
                       C34 8 20 24 0 40 Z"/>
  </defs>

  <g fill="#000">
    <path fill="none" stroke="#000" stroke-width="5" stroke-linecap="round"
          d="M${P0[0]} ${P0[1]}
${SEGMENTS.map(([c1, c2, e]) => `             C${c1[0]} ${c1[1]} ${c2[0]} ${c2[1]} ${e[0]} ${e[1]}`).join("\n")}"/>

    <!-- Petioles. Each ends at its leaf's centre, so the join hides under the
         blade. -->
    <g fill="none" stroke="#000" stroke-width="4" stroke-linecap="round">
${petioles.join("\n")}
    </g>

${uses.join("\n")}
  </g>
</svg>
`;

writeFileSync("public/vine.svg", svg, "utf8");
console.log(`wrote public/vine.svg — ${LEAVES.length + 1} leaves, 200x800`);
